### PR TITLE
fix title_location for corrplot (fix #141)

### LINKED ISSUE #141: Title position for corrplot
The corrplot recipe doesn't allow for any position other than a central one currently. All these commands produce the same output

`corrplot(rand(100,4),title="(A)",title_loc=:left)`

`corrplot(rand(100,4),title="(A)",title_loc=:centre)`

`corrplot(rand(100,4),title="(A)",title_loc=:right)`

### PR DESCRIPTION
**Pull request by daschw**
```julia
using StatPlots
corrplot(randn(100,4),title="(A)",title_loc=:left)
corrplot(randn(100,4),title="(A)",title_loc=:right)
corrplot(randn(100,4),title="(A)",title_loc=:center)
```

corrplot_left

corrplot_right

corrplot_center

### CODE REVIEW

File: src/corrplot.jl [hunk 1]
```diff
@@ -65,7 +69,7 @@ end
                 #above diag... hist2d
                 @series begin
                     seriestype := get(plotattributes, :seriestype, :histogram2d)
-                    if title != "" && i == 1 && j == div(n,2)+1
+                    if title != "" && i == 1 && ((title_location == :center && j == div(n,2)+1) || (title_location == :right && j == n))
```
Comment (mkborregaard) [inline src/corrplot.jl]: Maybe set `title_location := :left` if `n` is an even number? It would move it further towards the center, not sure it would really look nicer though.

Comment (daschw) [reply src/corrplot.jl]: That would probably look nicer. Thanks for the hint!

**Comment by daschw** [comment]
corrplot_center

better?

**Comment by mkborregaard** [comment]
Yes I think so :-)

**Comment by mkborregaard** [comment]
What default theme do you use (just curious)?

**Comment by daschw** [comment]
`:wong`
